general:
  verbose: true
  productiveBranch: 'master-qa'
  buildTool: 'npm'
  gitHttpsCredentialsId: 'GitHub-emobility-ci-build'
  githubTokenCredentialsId: 'GitHub-token-emobility-ci-build'

stages:

  Central Build:
    executeSonarScan: false
    sonarExecuteScan: true

  IPScan and PPMS:
    ppmsCredentialsId: 'ppms-i030367-access'
    executeWhitesourceScan: true
    whitesourceProductName: 'SHC - SAP E-MOBILITY UI 1.0'
    whitesourceProjectNames: ['ev-dashboard - 1'] # needed for automation of mapping requests
    whitesourceProductToken: 'c96d2e0dd15c4c359d224d8ae51bc2119f9721988d344aaea3cecd0dad2b6196'
    whitesourceProductVersion: '1'
    whitesourceUserTokenCredentialsId: 'whitesourceUserTokenEmobility'
    
  Additional Unit Tests:
    karmaExecuteTests: false
    
  #Acceptance:
  #  cloudFoundryDeploy: true
  #  cloudFoundry:
  #    org: 'SAP IT Cloud_sapitcfd'
  #    space: e-Mobility-dev
  #    credentialsId: scp-i030367-access    
      
  Security:
    executeCheckmarxScan: true
    checkmarxExecuteScan: false
    executeWhitesourceScan: false

  Release:
    cloudFoundry/org: SAP_IT_Cloud_sapitcft
    cloudFoundry/space: e-mobility
    cloudFoundry/credentialsId: scp-i030367-access
    
steps:

  sonarExecuteScan:
    instance: 'SAP SonarQube Enterprise'
            
  executeWhitesourceScan:
    scanType: 'npm'
    dockerImage: node:lts
   
  executeCheckmarxScan:
    checkmarxProject: 'ev-dashboard'
    #checkmarxGroupId: '29091a00-0dbc-4d06-b78b-32ab0ef54cdc'
    checkmarxGroupId: 'f8bb43bd-9a38-4e6a-a932-6a8159817e41'
    preset: 100131 #SAP_Default_Typescript
    checkmarxCredentialsId: 'checkmarx-access'
    filterPattern: '!**/node_modules/**, !**/coverage/**, !**/coverage-tmp/**, !**/.xmake/**, !**/tests/**, !**/jest.config.js, !**/*_test.go, !**/vendor/**/*.go, **/*.html, **/*.xml, **/*.go, **/*.py, **/*.js, **/*.scala, **/*.ts, **/*.tsx'
      
  sapCheckPPMSCompliance:
    ppmsID: '73554900100200014453'
    uploadChangeRequest: true
    createBuildVersion: true
    buildVersion: '{{.Major}}.{{.Minor}}'
