name: Unit Tests CI

on:
  push:
    branches:
      - master
      - master-qa
      - migrate-tests
  pull_request:
    branches:
      - master-qa

jobs:
  unit-tests-submodules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Install NodeJs ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - name: Install NodeJs Packages
      run: npm ci
    - name: Build sources
      run: |
        npm run build:dev
    - name: Start Dashboard
      run: |
        npm run start & sleep 10
    - name: Run Integration Tests
      run: npm run test
